# Generated by Django 3.0.7 on 2020-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_editor',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post_youtuber',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
