# Generated by Django 3.0.7 on 2020-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200614_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='datetime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_editor',
            name='datetime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_youtuber',
            name='datetime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_youtuber',
            name='rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='post_editor',
            name='datetime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post_youtuber',
            name='datetime',
            field=models.TextField(null=True),
        ),
    ]
