# Generated by Django 3.0.7 on 2020-06-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200622_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
