# Generated by Django 3.0.7 on 2020-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_youtuber',
            name='etc_require',
            field=models.TextField(null=True),
        ),
    ]
