# Generated by Django 3.0.7 on 2020-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_youtuber_etc_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_youtuber',
            name='etc_require',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
