# Generated by Django 3.0.7 on 2020-06-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200626_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
